<?php
$res_clients = array(
	"flags_admin" => array(
		"A"			=> 		"Accept Vote",
		"B"			=> 		"Menu RCon Vote",
		"C"			=> 		"Cancel Vote",
		"D"			=> 		"Menu Question Vote",
		"E"			=> 		"Ma Rates",
		"F"			=> 		"Burn",
		"G"			=> 		"No Clip Mode",
		"H"			=> 		"War",
		"I"			=> 		"Mute",
		"J"			=> 		"Reset All Ranks",
		"K"			=> 		"Cash",
		"L"			=> 		"RCon Say",
		"M"			=> 		"Admin Skins",
		"N"			=> 		"Set Skins",
		"O"			=> 		"Drop C4",
		"P"			=> 		"Set Client Flags",
		"Q"			=> 		"Console Question Vote",
		"R"			=> 		"RCon Vote",
		"S"			=> 		"Set Skin Colour",
		"T"			=> 		"Time Bomb",
		"U"			=> 		"Fire Bomb",
		"V"			=> 		"Map Vote",
		"W"			=> 		"Freeze Bomb",
		"X"			=> 		"Health",
		"Y"			=> 		"Beacon",
		"Z"			=> 		"Give Item",
		"a"			=> 		"Private Say",
		"b"			=> 		"Non Permanent Ban",
		"c"			=> 		"Map Change",
		"d"			=> 		"Drug",
		"e"			=> 		"Explode",
		"f"			=> 		"Freeze",
		"g"			=> 		"Swap Player",
		"i"			=> 		"Blind",
		"k"			=> 		"Kick",
		"l"			=> 		"Slap",
		"m"			=> 		"Slay",
		"o"			=> 		"Admin Chat",
		"p"			=> 		"Sound",
		"q"			=> 		"RCon Menu Level 1",
		"q2"		=>		"RCon Menu Level 2",
		"q3"		=>		"RCon Menu Level 3",
		"r"			=> 		"RCon",
		"s"			=> 		"Admin Say",
		"t"			=> 		"Teleport",
		"v"			=> 		"Random Map Vote",
		"w"			=> 		"Restrict Weapons",
		"x"			=> 		"CExec",
		"y"			=> 		"CExec Menu",
		"z"			=> 		"Config",
		"admin"		=> 		"Basic Admin",
		"client"	=> 		"Create Clients And Accesses",
		"grav"		=> 		"Per Player Gravity",
		"pban"		=> 		"Permanent Ban",
		"spray"		=>		"Spray Tag Tracking",
	),

	"flags_immunity" => array(
		"a"			=> 		"Name Tag Kick",
		"b"			=> 		"Ban",
		"c"			=> 		"Balance Team",
		"d"			=> 		"Drug",
		"e"			=> 		"Burn",
		"f"			=> 		"Freeze",
		"g"			=> 		"Swap Player",
		"h"			=> 		"Mute",
		"i"			=> 		"Blind",
		"k"			=> 		"Kick",
		"l"			=> 		"Slap",
		"m"			=> 		"Slay",
		"n"			=> 		"Reserved Slot Kick",
		"o"			=> 		"Set Skin",
		"p"			=> 		"Reserved Skin",
		"q"			=> 		"Time Bomb",
		"r"			=> 		"Fire Bomb",
		"s"			=> 		"Freeze Bomb",
		"t"			=> 		"Teleport",
		"u"			=> 		"Beacon",
		"v"			=> 		"Ghost",
		"w"			=> 		"Give Item",
		"x"			=> 		"CExec",
		"y"			=> 		"Colour",
		"afk"		=> 		"AFK Manager",
		"autojoin"	=> 		"Force Autojoin",
		"grav"		=> 		"Per Player Gravity",
		"ping"		=> 		"Ping",
	),
);

asort($res_clients['flags_admin']);
asort($res_clients['flags_immunity']);
?>